services:
  web:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: loa_service
    restart: always
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis

  celery_worker:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: loa_celery_worker
    command: uv run celery -A core.celery.celery_app worker --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
      - web

  celery_beat:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: loa_celery_beat
    command: uv run celery -A core.celery.celery_app beat --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
      - web

  redis:
    image: redis:7
    container_name: loa_redis
    restart: always
    ports:
      - "6379:6379"
